// T003: rpg-core carries the whole B01 domain layer.
// Constitution III.1 / FR-015: NO Paper/Bukkit dependency here, not even compileOnly.
// Everything in this module must be unit-testable without a running server.
dependencies {
    // No runtime dependencies at all. Lombok and MapStruct are applied to every module from the
    // root build, but both are compile-time only and leave nothing in the produced classes -
    // verified against the generated bytecode.
}
